### PR TITLE
Travis fix ?

### PR DESCRIPTION
**Pull request by rselwyn**

### CODE REVIEW

**Comment by DeckardKane** [comment]
Does this need to be merged? The Slack notifications are working without these changes.

**Comment by rselwyn** [comment]
@DeckardKane Yes.  The notifications worked because I changed the travis file (the travis file that runs is the one on the PR, not master).

**Comment by DeckardKane** [comment]
LGTM

**Comment by DeckardKane** [comment]
It looks like you removed failure messages though-am I correct in thinking that?

**Comment by rselwyn** [comment]
@DeckardKane according to the documentation, that is a default (what I had).  The documentation is a little bit shaky so this may need to be changed.

**Comment by DeckardKane** [comment]
Fair enough, we can definitely revisit it later if things are wonky. Thanks for all your work Robbie!

**Comment by rselwyn** [comment]
My suggestion is to try and make PR that won't pass and make sure the notifications work.

**Pull request merged**
