### PR TITLE
Add Lovecraftian Horror

### PR DESCRIPTION
**Pull request by JoeyKL**
The team could use a little more cosmic dread.

### CODE REVIEW

**Comment by DeckardKane** [comment]
I'm so tempted to approve this because I love it so much

**Comment by Naqu6** [comment]
Dont feed the trolls

**Comment by DeckardKane** [comment]
I am a subscriber to that particular internet axiom, but I'm not sure how it applies? I mean, I guess his commit could be seen as trolling, but if so, it failed to get the angry/confused response that trolling is often associated with out of me. Instead, I understood his reference, and appreciated it :)

**Comment by Naqu6** [comment]
I mean, joey wanst supposed to do this pull request, and it provides no
real progress. We could make him a branch

**Comment by DeckardKane** [comment]
Sure, but humor is always nice :D

**Comment by rselwyn** [comment]
@DeckardKane We should either merge this or close it, your choice :smile:

**Comment by DeckardKane** [comment]
And with that, the Victorian horrorlord was laid to rest once again.

**Pull request closed without merging**
