### PR TITLE
removed old code

### PR DESCRIPTION
**Pull request by rselwyn**
Removing the old front end.

### CODE REVIEW

**Comment by rselwyn** [comment]
This can be merged.

**Comment by DeckardKane** [comment]
Did you decide to not further pursue these features?

**Comment by rselwyn** [comment]
@DeckardKane I was under the impression that Ryan was working on something new.

**Comment by DeckardKane** [comment]
We are, but I don't want to discourage you from pursuing this unless you are tired of it. If that's the case, I'll merge this.

**Pull request closed without merging**
