### PR TITLE
Fixed pause scraping

### PR DESCRIPTION
**Pull request by Naqu6**

### CODE REVIEW

**Comment by Naqu6** [comment]
@DeckardKane

**Comment by rselwyn** [comment]
@Naqu6.  Could you squash your commits into two commits?

**Comment by DeckardKane** [comment]
Huh. This is strange. Travis is not reporting any issues, but when I run this I get a syntax error. Might just be my environment acting up, will investigate.

**Comment by rselwyn** [comment]
Not just you.  I was getting an error.

**Comment by Naqu6** [comment]
are you guys running off of portal?

**Comment by Naqu6** [comment]
with the latest push?

**Comment by DeckardKane** [comment]
Yes, check Slack for details, but I cleared up all the portal vs. Portal stuff, got the latest version of portal, then ran it, same problem.

**Comment by DeckardKane** [comment]
Can't merge this unless I know what db changes are being migrated. You added a password object? I'm assuming this is for creating a student portal? I really like that idea. Django is asking for a default value when I try to migrate that change, what should I tell it?

**Comment by Naqu6** [comment]
Password object is commented out, that code is still in Development

**Comment by DeckardKane** [comment]
Um, are you certain about that? Django is picking it up as a change.

**Pull request closed without merging**
