### PR TITLE
Front end

### PR DESCRIPTION
**Pull request by rselwyn**
Added the front-end home page with a features list and team calendar window.  The back-end interface has not been complete.  I want to pull this because it is 12 commits ahead.  @DeckardKane if you don't want to pull the branches, you don't have to.  I was just thinking out of best git practices, we would merge.

### CODE REVIEW

**Comment by Naqu6** [comment]
Robbie please dont attempt to use the database w/ php it conflicts with all
of Django

**Comment by rselwyn** [comment]
Actually, this is just the HTML and CSS of the online portal.  No backend has been implemented.

**Comment by Naqu6** [comment]
In what language

**Comment by DeckardKane** [comment]
Yeah, truth be told, I don't know if I'm qualified to know what the best Git practice is (but I'm learning), but I was figuring merging would be a good idea, so I think you're all good. There's actually zero potential for problems right now because master was pretty much empty anyway. 

I think Ryan and I can aim to have a serviceable version of the work we've been doing with Django this coming Monday or Tuesday (we're honestly pretty much done already, but it's probably worth going through and cleaning up a little bit), all of our work is currently in the dev branch.

**Pull request merged**
