### PR TITLE
Fixed the regex pattern so it has to be 8 numbers or 14 numbers

### PR DESCRIPTION
**Pull request by rselwyn**

### CODE REVIEW

**Comment by DeckardKane** [comment]
Uh, again, it is entirely possible you know something I don't Robbie, but why exactly did you do this? That's the regex pattern for the input box on the page itself, not the regex pattern for scraping the database. And even if this was what you meant to do, this regex pattern was already functional to begin with.

**Comment by DeckardKane** [comment]
I am not satisfied with the tone of my previous comment. To be clear, this is totally cool, I am just a lame coder and I am confused as to what this fixes. If you could elaborate for me (being the old man that I am), that would be even cooler :)

**Comment by rselwyn** [comment]
Sorry Peter.  AFAIK, with the previous version, someone could enter `MOOOOOOO` (at `/ScanCard`) and it would pass (although it would say entry not found eventually).  With this, the user must enter numbers.  Don't merge this yet, I'm going to make it better.

**Comment by rselwyn** [comment]
I'll fix this in a few mins.

**Comment by DeckardKane** [comment]
Oh, that would definitely need fixing! That being said, I just ran a test off `master` and it is impossible to enter letters.

**Comment by rselwyn** [comment]
Closing this for now.  When I have time later, I might fix this up.

**Pull request closed without merging**
